// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekTarifleri.Models;

#nullable disable

namespace YemekTarifleri.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117191016_AddImagePathToTarifModel")]
    partial class AddImagePathToTarifModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("YemekTarifleri.Models.TarifModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HazirlamaSuresi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .HasColumnType("TEXT");

                    b.Property<string>("Malzemeler")
                        .HasColumnType("TEXT");

                    b.Property<string>("Yapilis")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZorlukSeviyesi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tarifler");
                });
#pragma warning restore 612, 618
        }
    }
}
